schema_version: 1

context:
  version: "0.2.1"

package:
  name: fastscheduler
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fastscheduler/fastscheduler-${{ version }}.tar.gz
  sha256: 3ee84c9bc943c65b9493c8d8cacdcf8ea14b22cb57e4637cbc313a61e20ceda9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - sqlmodel >=0.0.31

tests:
  - python:
      imports:
        - fastscheduler
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Simple, lightweight task scheduler for Python with async support
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/fastscheduler/

extra:
  recipe-maintainers:
    - thewchan
